### ISSUE TITLE
What the hell happened here? 

### ISSUE THREAD

**Issue by pedramsafaei** [YifengQ/CS326-Color-Sampler#1]
https://github.com/YifengQ/CS326-Color-Sampler/blob/cb9bff547f300fa94a2fa4b38ef8133a42312ae1/colorsampler.java#L161

**Comment by YifengQ** [comment]
Solved

**Comment by pedramsafaei** [comment]
> Solved

u sure?

**Comment by YifengQ** [comment]
100%
